[versions]
minecraft = '1.21.11-R0.1-SNAPSHOT'
paperweight = "2.0.0-beta.19"
jedis = "5.1.0"
mongoDriver = "5.7.0-alpha0"
commandapi = "11.0.0"
shadow = "9.2.2"
anvilgui = "1.10.11-SNAPSHOT"
worldguard = "7.0.10"
velocity = "3.4.0-SNAPSHOT"
kubernetes = "7.3.1"
jetbrainsannotations = "26.0.2-1"
entitylib = "3.0.3-SNAPSHOT"
packetevents = "2.11.1"
limbo = "0.7.9-ALPHA"
adventure = "4.25.0"
authlib = "3.13.56"

[libraries]
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
mongo = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongoDriver" }
commandapi = { module = "dev.jorel:commandapi-paper-core", version.ref = "commandapi" }
paper =  { module = "io.papermc.paper:paper-api", version.ref = "minecraft"}
anvilgui = { module = "net.wesjd:anvilgui", version.ref = "anvilgui" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
kubernetes = { module = "io.fabric8:kubernetes-client", version.ref = "kubernetes" }
jetbrainsannotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsannotations" }
entitylib = { module = "io.github.tofaa2:spigot", version.ref = "entitylib" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
limbo = { module = "com.loohp:Limbo", version.ref = "limbo" }
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
authlib = { module = "com.mojang:authlib", version.ref = "authlib" }

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
shadow = { id =  "com.gradleup.shadow", version.ref = "shadow" }