[versions]
paper = '1.21.11-R0.1-SNAPSHOT'
paperweight = "2.0.0-beta.19"
jedis = "5.1.0"
mongoDriver = "5.7.0-alpha0"

[libraries]
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
mongo = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongoDriver" }

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
